#9 entidades
HackathonOrc/hackathonTime5 pull request #14
Opened 2021-07-05 18:40 UTC by JFNascimento99

Foi criada os Schemas das funções Like, Post e User, e já iniciei a criação dos Controllers dos mesmos

2021-07-06 00:09 UTC, Phe0 commented on server/src/schemas/userSchema.ts
> +const validator = require("mongoose-validator");
estão usando esse pacote mas não adicionaram ele no projeto

2021-07-07 19:21 UTC, Victor-Buendia requested changes

2021-07-07 19:21 UTC, Victor-Buendia commented on server/src/controllers/likeController.ts
> +                res.status(400).json({message: 'Não foi possivel atualizar o usuário'});
Trocar 'usuário' por 'like'

2021-07-07 19:21 UTC, Victor-Buendia commented on server/src/controllers/likeController.ts
> +            res.status(200).json({message: 'Usuário atualizado com sucesso'});
Trocar 'usuário' por 'like'

2021-07-07 19:21 UTC, Victor-Buendia commented on server/src/controllers/likeController.ts
> +            res.status(400).json({message: 'Ocorreu um erro ao atualizar o loke'});
Arrumar a grafia de 'loke' para 'like'

2021-07-07 19:21 UTC, Victor-Buendia commented on server/src/controllers/modeloController.ts
> +}
Remover este arquivo de modelo.

2021-07-07 19:21 UTC, Victor-Buendia commented on server/src/controllers/userController.ts
> +                res.status(400).json({message: 'Não foi possível atualizar o usuário'});
O erro aqui deveria ser "Usuário não foi encontrado"

2021-07-07 19:21 UTC, Victor-Buendia commented on server/src/controllers/userController.ts
> +            res.status(200).json({ message: 'Usuário deletado com sucesso'});
Aqui deu erro, então a mensagem não pode ser de "SUCESSO"

2021-07-09 16:58 UTC, merged